[tool.ruff]
line-length = 100
target-version = "py310"
src = ["scripts"]
exclude = [".venv", "runtime", "__pycache__"]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
]
ignore = []

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]

