name: CI
on: [push, pull_request]

permissions:
  contents: read
  id-token: write  # required for OIDC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Test
        run: |
          source .venv/bin/activate
          pytest --cov=scripts --cov-report=xml

      - name: Upload coverage to Codecov (OIDC)
        # Skip on forks, run only on your repo
        if: ${{ github.repository == 'carjes232/multilingual-multihop-rag' }}
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
