name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
<<<<<<< HEAD
        python-version: '3.11'
=======
        python-version: '3.10'
>>>>>>> 52926b9de47da0bacdeeb0882f84a1f9fc20f840

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Run ruff
      run: |
        source .venv/bin/activate
        ruff .

    - name: Run tests and coverage
      run: |
        source .venv/bin/activate
        pytest --cov=scripts --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
